spring:
  application:
    name: test
  profiles:
    #默认启动
    active: dev
  cloud:
    consul:
      discovery:
        service-name: test
        deregister: true
---
server:
  port: 8018
spring:
  profiles: dev
  cloud:
    consul:
      host: 192.168.2.119
      port: 8500
---
server:
  port: 8080
spring:
  profiles: test
  cloud:
    consul:
      host: 172.31.0.3
      port: 8500
---
server:
  port: 8080
spring:
  profiles: prod